### ISSUE TITLE
Central Dashboard Manage Contributors Unable to add new contributor for user: [object Object]

### ISSUE THREAD

**Issue by amybachir** [argoflow/argoflow-aws#234]
Hi! I'm running off latest commit in argoflow as of today (commit hash cdce0fc). I'm unable to add a contributor to my workspace. Attempting to a add a user returns the following error:
`Unable to add new contributor for user: [object Object]`

![image](https://user-images.githubusercontent.com/19543576/136593822-52955651-8a95-41e8-9ee9-fb060dfa1238.png)

**Comment by GetOn4** [comment]
Do you have some news on this?

**Comment by amybachir** [comment]
@GetOn4 Nope and I haven't had a chance to troubleshoot this yet. I think it might be a problem in the central dashboard cuz I can add contributors manually through `kubectl` by following the [documentation on kubeflow](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#managing-contributors-manually)

I did notice that `add-contributor` endpoint sometimes gets a 404 and sometimes a 400 response code
![image](https://user-images.githubusercontent.com/19543576/141507793-b39bd12c-8462-49fc-9877-c8b2bc53235a.png)

This is the error log from the central dashboard pod:
```
Unable to add new contributor for abachir: [object Object]
Unable to add new contributor for abachir: [object Object]
Unable to add new contributor for abachir: Error: getaddrinfo EAI_AGAIN profiles-kfam.kubeflow
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) Error: getaddrinfo EAI_AGAIN profiles-kfam.kubeflow
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'profiles-kfam.kubeflow'
}
Unable to add new contributor for abachir: Error: getaddrinfo EAI_AGAIN profiles-kfam.kubeflow
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) Error: getaddrinfo EAI_AGAIN profiles-kfam.kubeflow
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'profiles-kfam.kubeflow'
}
Unable to add new contributor for abachir: Error: getaddrinfo EAI_AGAIN profiles-kfam.kubeflow
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) Error: getaddrinfo EAI_AGAIN profiles-kfam.kubeflow
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'profiles-kfam.kubeflow'
}
Unable to add new contributor for abachir: Error: getaddrinfo EAI_AGAIN profiles-kfam.kubeflow
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) Error: getaddrinfo EAI_AGAIN profiles-kfam.kubeflow
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'profiles-kfam.kubeflow'
}```
